`define ALU_OP_WIDTH 4   ///PARAM CORE

`define ALU_OP_ADD  `ALU_OP_WIDTH'd0   ///PARAM CORE
`define ALU_OP_SLL  `ALU_OP_WIDTH'd1   ///PARAM CORE
`define ALU_OP_XOR  `ALU_OP_WIDTH'd4   ///PARAM CORE
`define ALU_OP_OR   `ALU_OP_WIDTH'd6   ///PARAM CORE
`define ALU_OP_AND  `ALU_OP_WIDTH'd7   ///PARAM CORE
`define ALU_OP_SRL  `ALU_OP_WIDTH'd5   ///PARAM CORE
`define ALU_OP_SEQ  `ALU_OP_WIDTH'd8   ///PARAM CORE
`define ALU_OP_SNE  `ALU_OP_WIDTH'd9   ///PARAM CORE
`define ALU_OP_SUB  `ALU_OP_WIDTH'd10   ///PARAM CORE
`define ALU_OP_SRA  `ALU_OP_WIDTH'd11   ///PARAM CORE
`define ALU_OP_SLT  `ALU_OP_WIDTH'd12   ///PARAM CORE
`define ALU_OP_SGE  `ALU_OP_WIDTH'd13   ///PARAM CORE
`define ALU_OP_SLTU `ALU_OP_WIDTH'd14   ///PARAM CORE
`define ALU_OP_SGEU `ALU_OP_WIDTH'd15   ///PARAM CORE
