//Register File
`define REG_SEL 5   ///PARAM CORE
//`define REG_NUM 2**`REG_SEL
`define REG_NUM 32   ///PARAM CORE

//Instruction
`define IMM_TYPE_WIDTH 2   ///PARAM CORE
`define IMM_I `IMM_TYPE_WIDTH'd0   ///PARAM CORE
`define IMM_S `IMM_TYPE_WIDTH'd1   ///PARAM CORE
`define IMM_U `IMM_TYPE_WIDTH'd2   ///PARAM CORE
`define IMM_J `IMM_TYPE_WIDTH'd3   ///PARAM CORE

//Important Wire
`define DATA_LEN 32   ///PARAM CORE
`define INSN_LEN 32   ///PARAM CORE
`define ADDR_LEN 32   ///PARAM CORE
`define ISSUE_NUM 2   ///PARAM CORE
`define ENTRY_POINT `ADDR_LEN'h0   ///PARAM CORE
//`define REQDATA_LEN 2

//Decoder
`define RS_ENT_SEL 3   ///PARAM CORE
`define RS_ENT_ALU 1   ///PARAM CORE
`define RS_ENT_BRANCH 2   ///PARAM CORE
`define RS_ENT_JAL `RS_ENT_BRANCH   ///PARAM CORE
`define RS_ENT_JALR `RS_ENT_BRANCH   ///PARAM CORE
`define RS_ENT_MUL 3   ///PARAM CORE
`define RS_ENT_DIV 3   ///PARAM CORE
`define RS_ENT_LDST 4   ///PARAM CORE

//RS
`define ALU_ENT_SEL 3   ///PARAM CORE
`define ALU_ENT_NUM 8   ///PARAM CORE
`define BRANCH_ENT_SEL 2   ///PARAM CORE
`define BRANCH_ENT_NUM 4   ///PARAM CORE
`define LDST_ENT_SEL 2   ///PARAM CORE
`define LDST_ENT_NUM 4   ///PARAM CORE
//`define LDST_ENT_SEL 3
//`define LDST_ENT_NUM 8
`define MUL_ENT_SEL 1   ///PARAM CORE
`define MUL_ENT_NUM 2   ///PARAM CORE

//STOREBUFFER
`define STBUF_ENT_SEL 5   ///PARAM CORE
`define STBUF_ENT_NUM 32   ///PARAM CORE

//BTB
`define BTB_IDX_SEL 9   ///PARAM CORE
`define BTB_IDX_NUM 512   ///PARAM CORE
//`define BTB_IDX_NUM 2**`BTB_IDX_SEL
//`define BTB_TAG_LEN `ADDR_LEN-3-`BTB_IDX_SEL
`define BTB_TAG_LEN 20   ///PARAM CORE

//Gshare
`define GSH_BHR_LEN 10   ///PARAM CORE
`define GSH_PHT_SEL 10   ///PARAM CORE
`define GSH_PHT_NUM 1024   ///PARAM CORE
//`define GSH_PHT_NUM 2**`GSH_PHT_SEL

//TagGenerator

//`define SPECTAG_LEN 1+`BRANCH_ENT_NUM
`define SPECTAG_LEN 5   ///PARAM CORE
//`define BRDEPTH_LEN `SPECTAG_LEN
`define BRDEPTH_LEN 5   ///PARAM CORE

//Re-Order Buffer
`define ROB_SEL 6   ///PARAM CORE
//`define ROB_NUM 2**`ROB_SEL
`define ROB_NUM 64   ///PARAM CORE
`define RRF_SEL `ROB_SEL   ///PARAM CORE
`define RRF_NUM `ROB_NUM   ///PARAM CORE

//src_a
`define SRC_A_SEL_WIDTH 2   ///PARAM CORE
`define SRC_A_RS1  `SRC_A_SEL_WIDTH'd0   ///PARAM CORE
`define SRC_A_PC   `SRC_A_SEL_WIDTH'd1   ///PARAM CORE
`define SRC_A_ZERO `SRC_A_SEL_WIDTH'd2   ///PARAM CORE

//src_b
`define SRC_B_SEL_WIDTH 2   ///PARAM CORE
`define SRC_B_RS2  `SRC_B_SEL_WIDTH'd0   ///PARAM CORE
`define SRC_B_IMM  `SRC_B_SEL_WIDTH'd1   ///PARAM CORE
`define SRC_B_FOUR `SRC_B_SEL_WIDTH'd2   ///PARAM CORE
`define SRC_B_ZERO `SRC_B_SEL_WIDTH'd3   ///PARAM CORE

`define MEM_TYPE_WIDTH 3   ///PARAM CORE
`define MEM_TYPE_LB  `MEM_TYPE_WIDTH'd0   ///PARAM CORE
`define MEM_TYPE_LH  `MEM_TYPE_WIDTH'd1   ///PARAM CORE
`define MEM_TYPE_LW  `MEM_TYPE_WIDTH'd2   ///PARAM CORE
`define MEM_TYPE_LD  `MEM_TYPE_WIDTH'd3   ///PARAM CORE
`define MEM_TYPE_LBU `MEM_TYPE_WIDTH'd4   ///PARAM CORE
`define MEM_TYPE_LHU `MEM_TYPE_WIDTH'd5   ///PARAM CORE
`define MEM_TYPE_LWU `MEM_TYPE_WIDTH'd6   ///PARAM CORE

`define MEM_TYPE_SB  `MEM_TYPE_WIDTH'd0   ///PARAM CORE
`define MEM_TYPE_SH  `MEM_TYPE_WIDTH'd1   ///PARAM CORE
`define MEM_TYPE_SW  `MEM_TYPE_WIDTH'd2   ///PARAM CORE
`define MEM_TYPE_SD  `MEM_TYPE_WIDTH'd3   ///PARAM CORE

`define MD_OP_WIDTH 2   ///PARAM CORE
`define MD_OP_MUL `MD_OP_WIDTH'd0   ///PARAM CORE
`define MD_OP_DIV `MD_OP_WIDTH'd1   ///PARAM CORE
`define MD_OP_REM `MD_OP_WIDTH'd2   ///PARAM CORE

`define MD_OUT_SEL_WIDTH 2   ///PARAM CORE
`define MD_OUT_LO  `MD_OUT_SEL_WIDTH'd0   ///PARAM CORE
`define MD_OUT_HI  `MD_OUT_SEL_WIDTH'd1   ///PARAM CORE
`define MD_OUT_REM `MD_OUT_SEL_WIDTH'd2   ///PARAM CORE

